### ISSUE TITLE
In rendering context variables that were not provided should be initialized

### ISSUE THREAD

**Issue by patrys** [gregmuellegger/django-floppyforms#163]
Currently only variables that were provided using `with` are passed to the templates. This breaks in two cases:

1. When an identically named variable exists in the outer scope, it will leak into the inner scope:

    ```html+django
    {% with label="foo" %}
        {% formrow bar %}
    {% endwith %}
    ```

    This will output a field labeled “foo” which may be unexpected and very hard to track as the variables could come from a different template file.

2. When using Django's [`string_if_invalid`](https://docs.djangoproject.com/en/1.8/ref/templates/api/#invalid-template-variables) to track errors in templates, uninitialized variables are no longer considered empty by the `default` filter:

    ```python
    # settings.py
    TEMPLATES = [{
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ...,
        'OPTIONS': {
            'debug': True,
            'context_processors': ...,
            'loaders': ...,
            'string_if_invalid': '<< MISSING VARIABLE "%s" >>',
        }
    }]
    ```

    ```html+django
    {% formrow bar %}
    ```

    This will output a field labelled “<< MISSING VARIABLE "label" >>” and with a help text of “<< MISSING VARIABLE "help_text" >>”.

If variables like `label`, `help_text` and `classes` were always initialized to `field.label`, `field.help_text` and so on then the row template itself would become simpler:

```html+django
{% with classes=field.css_classes label=label|default:field.label help_text=help_text|default:field.help_text %}
...
{% endwith %}
```

This `with` would be unnecessary.

**Comment by gregmuellegger** [comment]
Hi, sorry for my late response, I've been on a longer trip with no coding on the plan :)

I know the trouble you are having with the variables leaking into inner scopes. That's not ideal in some circumstances, but the idea is to mirror the semantics of Django's `{% include %}` template tag. You can isolate the scope by using the `only` keyword just as with the `include` tag, there is an example on this page: http://django-floppyforms.readthedocs.org/en/latest/templatetags.html 

The issue with the `string_if_invalid` has been discussed quite a while back: https://github.com/gregmuellegger/django-floppyforms/issues/37#issuecomment-6605001 it's a little tricky, since Django's template language behaves odd in a few places if you set the setting. However I only tried this back before the different template engines were introduced. But I'm afraid we are out of luck here to reliably support this setting in all circumstances. Maybe the link from above helps a little.

Regarding initializing the variables `label`, `help_text` etc: It's true, it would make the template code easier to read. However the goal of the template rendering of floppyforms is to put as much logic into the template in order to keep the rendering out of the python code. And if we pull the initialization into the template tag logic, then we miss out on the explicitness that we have right now in the templates, so that you know where the values come from etc.
Am I a little to puristic here, what do you think?

**Comment by patrys** [comment]
In our case we depend on `string_if_invalid` to make sure templates do not rely on incorrect/mistyped variables. This forces us to override the templates provided by `django-floppyforms` to avoid errors in output.

**Comment by gregmuellegger** [comment]
Does this trick make it work for you:

```
class Invalid(unicode):
    def __nonzero__(self):
        return False

TEMPLATE_STRING_IF_INVALID = Invalid('<INVALID>')
```

It did work in 2012 :) when I wrote the comment linked above.

**Comment by patrys** [comment]
That would change the behaviour of `string_if_invalid` and make it harder to detect errors in our templates. FWIW in our templates we consider `{{ undefined|default:'asd' }}` to be a bug.

**Comment by gregmuellegger** [comment]
Hm, that's quite tricky. I'm afraid I have to close the initial proposal for initializing the variables with a "won't fix" as this behaviour is intended. I'm quite sorry that this makes your life harder than it could be.

Do you have any other suggestions how we could come to a better solution? Maybe making everything work with the `TEMPLATE_STRING_IF_INVALID` might do the trick. Any efforts in that direction are welcome.
