### ISSUE TITLE
Unable to import floppyforms.gis, geometry widgets not available

### ISSUE THREAD

**Issue by foobarbaz2** [gregmuellegger/django-floppyforms#172]
/home/foo/anaconda2/envs/flightsayer/lib/python2.7/site-packages/floppyforms/__init__.py:16: UserWarning: Unable to import floppyforms.gis, geometry widgets not available
  "Unable to import floppyforms.gis, geometry widgets not available")

Ok, I get that this happens on "from . import gis", but I don't understand what's going on.

(Everything worked fine until this morning, after I upgraded some stuff on my computer, and now I'm seeing this message and AHHHHH)

**Comment by askoretskiy** [comment]
@foobarbaz2 How did you fix it?

**Comment by BakanovKirill** [comment]
@foobarbaz2 How did you fix it? +1

**Comment by chrnolte** [comment]
@foobarbaz2 How did you fix it? +1

**Comment by bnisevic** [comment]
How did you fix it? +1

**Comment by Wipqozn113** [comment]
Ran into the same issue. To figure out what wrong I edited floppyforms/__init__.py and removed the try/catch on "from . import gis" so I could see what error I was actually getting.

so this:
` 16 try:
 17     from . import gis
 18 except Exception:
 19     import warnings
 20     warnings.warn( 
 21         "Unable to import floppyforms.gis, geometry widgets not available")
 22 
 23 __version__ = '1.7.0'`

became this:

` 16 from . import gis`

This showed me the the "gdal" library wasn't installed. I tried install gdal with "pip install gdal", but I just ran into more issues about gdal not being installed. I eventually realized that the issue was that I needed to install gdal on my system, independent of python, and that Python makes use of it. 

I'm on macos, so that meant I needed to run:

`brew install gdal --HEAD`

Source: https://gis.stackexchange.com/questions/155403/installing-gdal-on-macosx

I suspect others might be running into the same issue. My suggestion would be to install the gdal library on your system or remove the try/except around "from . import gis" so you can see what error you're actually getting.

**Comment by ivancuric** [comment]
Running `brew install gdal --HEAD` produces compilation errors, but I managed to install  it from https://github.com/OSGeo/homebrew-osgeo4mac

Running into the same error.

Both `gdal2` and `gdal2-python` are visible in the `PATH`:
```
export PATH="/usr/local/opt/gdal2/bin:$PATH"
export PATH="/usr/local/opt/gdal2-python/bin:$PATH"
```

```
ogr2ogr --version
GDAL 2.2.2, released 2017/09/15
```
```

**Comment by thauk-copperleaf** [comment]
How can this warning be silenced/eliminated _without_ having to brew-install an external package?

**Comment by cjerdonek** [comment]
See [here](https://github.com/gregmuellegger/django-floppyforms/issues/189#issuecomment-379546682) for a simple work-around that doesn't require installing anything.

**Comment by marcossouz** [comment]
Running: `sudo apt-get install binutils libproj-dev gdal-bin`

source: https://docs.djangoproject.com/en/3.0/ref/contrib/gis/install/geolibs/
